image: privacybydesign/golang_sql:latest

stages:
  - build
    #  - package

before_script:
  - set -euxo pipefail

build:
  stage: build
  variables:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
    PACKAGE_NAME: github.com/privacybydesign/irma-gast
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 100 year
    paths:
      - artifacts/*
  script:
    - mkdir -p artifacts
    - cd waar
    - go build -a -ldflags '-extldflags "-static"' -o "../artifacts/irma-gast" .

      # docker:
      #   stage: package
      #   tags:
      #   - docker
      #   image: docker:stable
      #   script:
      #   - docker login -u irma-access -p $REGISTRY_TOKEN $REGISTRY
      #   - docker build -f Dockerfile -t $IMAGE .
      #   - docker push $IMAGE
